config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :courses
  resources :mentors
  resources :addresses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/mentor.rb
class Mentor < ApplicationRecord
    has_one :address, as: :addressable
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: %i[ show edit update destroy ]

  # GET /mentors or /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1 or /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors or /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to mentor_url(@mentor), notice: "Mentor was successfully created." }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1 or /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to mentor_url(@mentor), notice: "Mentor was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1 or /mentors/1.json
  def destroy
    @mentor.destroy!

    respond_to do |format|
      format.html { redirect_to mentors_url, notice: "Mentor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mentor_params
      params.require(:mentor).permit(:name, :email)
    end
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/mentors/_form.html.erb
<%= form_with(model: mentor) do |form| %>
  <% if mentor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
        <% mentor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentors/_mentor.html.erb
<div id="<%= dom_id mentor %>">
  <p>
    <strong>Name:</strong>
    <%= mentor.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= mentor.email %>
  </p>

</div>

app/views/mentors/edit.html.erb
<h1>Editing mentor</h1>

<%= render "form", mentor: @mentor %>

<br>

<div>
  <%= link_to "Show this mentor", @mentor %> |
  <%= link_to "Back to mentors", mentors_path %>
</div>

app/views/mentors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mentors</h1>

<div id="mentors">
  <% @mentors.each do |mentor| %>
    <%= render mentor %>
    <p>
      <%= link_to "Show this mentor", mentor %>
    </p>
  <% end %>
</div>

<%= link_to "New mentor", new_mentor_path %>

app/views/mentors/new.html.erb
<h1>New mentor</h1>

<%= render "form", mentor: @mentor %>

<br>

<div>
  <%= link_to "Back to mentors", mentors_path %>
</div>

app/views/mentors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mentor %>

<div>
  <%= link_to "Edit this mentor", edit_mentor_path(@mentor) %> |
  <%= link_to "Back to mentors", mentors_path %>

  <%= button_to "Destroy this mentor", @mentor, method: :delete %>
</div>